version: '3.4'

services:
  redis:
    restart: 'no'
    image: redis:alpine
    command: --loglevel verbose
    ports:
      - "6379:6379"
      
  rcli:
    restart: 'no'
    image: redis:alpine
    depends_on:
      - redis
    command: >
      sh -c 'redis-cli -h redis '

  phpredisadmin:
    restart: 'no'
    image: erikdubbelboer/phpredisadmin
    environment:
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379
    depends_on:
      - redis
    ports:
      - "8081:80"
